/*
 *This software is made by Dhruvin Bharatbhai Desai.
 */

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ComponentListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Dhruvin
 */
public class add_page extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public add_page() {
        initComponents();
    }
    
    public add_page(Mainframe MainObj) {
        initComponents();
        this.MainObj = MainObj;
    }
    
    public add_page(Mainframe MainObj, TaskTimer editTT, boolean mode, String task, Date date){
        this.MainObj = MainObj;
        this.edit_task_tt = editTT;
        this.edit_mode = mode;
        initComponents();
        this.task_text.setText(task);
        this.date_var.setDate(date);
        System.out.println(date.toString());
        this.time_var.setValue(date);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        task_text = new javax.swing.JTextArea();
        reset_button = new javax.swing.JButton();
        settask_button = new javax.swing.JButton();
        date_var = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        time_var = new javax.swing.JSpinner(sm);
        error_info = new javax.swing.JLabel();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(430, 150, 0, 0));
        setMinimumSize(new java.awt.Dimension(610, 510));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Date");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Task Description");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText(":");

        task_text.setColumns(20);
        task_text.setRows(5);
        task_text.setText(null);
        jScrollPane1.setViewportView(task_text);

        reset_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reset_button.setText("Reset");
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_buttonMouseClicked(evt);
            }
        });

        settask_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        settask_button.setText("Set Task");
        settask_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settask_buttonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Time");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText(":");

        JSpinner.DateEditor de = new JSpinner.DateEditor(time_var, "HH:mm:ss");
        time_var.setEditor(de);
        time_var.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        error_info.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        error_info.setForeground(new java.awt.Color(255, 0, 0));
        error_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cancel_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancel_button.setText("Cancel");
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Main_panelLayout = new javax.swing.GroupLayout(Main_panel);
        Main_panel.setLayout(Main_panelLayout);
        Main_panelLayout.setHorizontalGroup(
            Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_panelLayout.createSequentialGroup()
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Main_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Main_panelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Main_panelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_var, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time_var, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Main_panelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(error_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_panelLayout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settask_button, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        Main_panelLayout.setVerticalGroup(
            Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_var, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(time_var))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(error_info, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settask_button, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseClicked
        // TODO add_page your handling code here:
        date_var.setDate(null);
        task_text.setText(null);
        error_info.setText(null);
    }//GEN-LAST:event_reset_buttonMouseClicked

    private void settask_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settask_buttonMouseClicked
        // TODO add your handling code here:
        // Resetting error_info tag.
        cancel_button.setEnabled(false);
        reset_button.setEnabled(false);
        error_info.setText(null);
        boolean INFO_COMPLETE = true;
        // Checking if date is given.
        if(date_var.getDate() == null){
            System.out.println("Date not Set.");
            INFO_COMPLETE = false;
        }
        else{
            //System.out.println("Date: "+ date_var.getDate().toString());
            this.final_date = date_var.getDate().toString();
            
        }
        
        // Checking if task is given.
        if(task_text.getText().isEmpty()){
            System.out.println("Task not Set.");
            if(INFO_COMPLETE){
                error_info.setText("Task not specified!!!!");
            }
        }
        else{
            //System.out.println("Task: "+ task_text.getText());
            this.final_task = task_text.getText();
            if(!INFO_COMPLETE){
                error_info.setText("Date Not Given!!!!!");
                INFO_COMPLETE = true;
            }
        }
        
        if(!INFO_COMPLETE){
            error_info.setText("Date and Task not specified!!!!!!!!");
        }
        
        String time[] = time_var.getValue().toString().split(" ");
        this.final_time = time[3];
        String temp_date = null;
        long temptime = 0;
        
        if(final_date != null){
            time = this.final_date.split(" ");
            // Fri Dec 27 00:00:00 EST 2019
            time[3] = this.final_time;
            temp_date = time[0]+" "+time[1]+" "+time[2]+" "+time[3]+" "+time[4]+" "+time[5];    
            this.final_date = temp_date;
            time = null;

            //CountDown time calculation.
            DateFormat df = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy");
            Date user_deadline_date;
            
            try {
                user_deadline_date = df.parse(temp_date);
                Calendar today = Calendar.getInstance();
                long today_in_milli = today.getTimeInMillis();
                temptime = user_deadline_date.getTime() - today_in_milli;
            } catch (ParseException ex) {
                Logger.getLogger(add_page.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(temptime < 1){
                error_info.setText(error_info.getText()+"  Invalid Time.");
            }

        }
        
        // Checking to exit or not.
        if(error_info.getText() == null || error_info.getText().isEmpty()){
            // Task Addition logic.
            try {
                if(this.edit_mode){
                    this.MainObj.TaskListEditDelete(edit_task_tt);
                    this.edit_task_tt.TTSetVariable(this.final_task, this.final_date, this.final_time);
                    edit_task_tt.count_time = temptime;
                    edit_task_tt.area.setText(this.final_task);
                    edit_task_tt.time_label.setText("Calculating.  .  .  .  .");
                    edit_task_tt.content_panel.setBackground(new Color(240,240,240));
                    edit_task_tt.CountDownTimer();
                    this.MainObj.TaskListEditModifier(edit_task_tt);
                    System.out.println("Task Edited........ Successfull");
                }
                else{
                    TaskTimer tt = new TaskTimer(this.MainObj, this.final_task, this.final_date, this.final_time);
                    tt.count_time = temptime;
                    this.MainObj.TaskListModifier(tt);

                    System.out.println("New Task addition........ Successfull");    
                }
                
            } catch (Exception ferr){
                System.out.println(ferr.getStackTrace());
            }

            // Memory releasing logic. (Might need more research work)
            dispose();
            Destroyer();
        }
        cancel_button.setEnabled(true);
        reset_button.setEnabled(true);
        
    }//GEN-LAST:event_settask_buttonMouseClicked

    private void cancel_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseClicked
        // TODO add your handling code here:
        if(edit_mode){
            edit_task_tt.CountDownTimer();
        }
        dispose();
        Destroyer();
    }//GEN-LAST:event_cancel_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_page().setVisible(true);
            }
        });
    }

    private void Destroyer(){
        System.out.println("Destroying all add_page swing object.");
        
        for(Component comp : Main_panel.getComponents()){
//            if(comp instanceof Component){
//                //Destroyer();
//                System.out.println(comp);
//            }
            for(ComponentListener complist : comp.getComponentListeners()){
                comp.removeComponentListener(complist);
            }
            comp = null;
        }
        
        Main_panel.removeAll();
        Main_panel = null;
        System.out.println("All add_page swing object destroyed.");
    }
    
    public void finalize(){
        Destroyer();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_panel;
    private javax.swing.JButton cancel_button;
    private org.jdesktop.swingx.JXDatePicker date_var;
    private javax.swing.JLabel error_info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton settask_button;
    private javax.swing.JTextArea task_text;
    private javax.swing.JSpinner time_var;
    // End of variables declaration//GEN-END:variables
    private Mainframe MainObj;
    private TaskTimer edit_task_tt=null;
    private String final_date,final_time,final_task;
    private boolean edit_mode = false;
}
